### ISSUE TITLE
Doorhanger still displayed after clicking the "Go back one page" button

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-addon#105]
[Affected versions]:
- Firefox 62.0
- Firefox 63.0a1

- Firefox Monitor 2.1

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
Prefs you'll need to set in about:config:
- (boolean) extensions.fxmonitor.enabled - true
- (string) extensions.fxmonitor.breachListURL - https://haveibeenpwned.com/api/v2/breaches

[Steps to reproduce]:
1. Access in a new tab any of the sites from this list: https://docs.google.com/spreadsheets/d/1GYsLxXdCTlV5INzkpVBlpRPS3kfj-pTG7INOPSX6Up4/edit#gid=1389057478
2. Wait until the page is loaded and the doorhanger is displayed.
3. Click on the "Go back one page" button.

[Expected result]:
- The doorhanger is dismissed.

[Actual result]:
- The doorhanger is still displayed until you click on the URL bar . 

[Regression]:
- I don't think this is a regression.

[Notes]:
- Please look at the attached gif. 
![peek 2018-08-29 15-32](https://user-images.githubusercontent.com/42799381/44788487-d7e59880-aba2-11e8-9f06-de2144d79dc6.gif)

**Comment by nhnt11** [comment]
This is a bug in PopupNotifications - it doesn't handle going back to the newtab page (which seems to be a problematic "feature").

I don't think we should fix this here. The same issue is observed if you trigger a permission prompt (from permission.site for example) and click the back button.

@johannhof what do you think?

**Comment by nhnt11** [comment]
This is being tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1478348.
Closing this issue.
