### ISSUE TITLE
The doorhanger is displayed even if Firefox Monitor add-on is disabled 

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-addon#106]
[Affected versions]:

- Firefox 62.0
- Firefox 63.0a1

- Firefox Monitor 2.1

[Affected Platforms]:

- Windows 10 x64
- Windows 7 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
Prefs you'll need to set in about:config:
- (boolean) extensions.fxmonitor.enabled - true
- (string) extensions.fxmonitor.breachListURL - https://haveibeenpwned.com/api/v2/breaches

[Steps to reproduce]:
1. Access in a new tab any of the sites from this list: https://docs.google.com/spreadsheets/d/1GYsLxXdCTlV5INzkpVBlpRPS3kfj-pTG7INOPSX6Up4/edit#gid=1389057478
2.  Go ro about:addons -> Extensions and disable Firefox Monitor.
3. Access another link from the list in step 1.

[Expected result]:
- The doorhanger is not displayed.

[Actual result]:
- The doorhanger is still displayed abd the icon changes color.

[Regression]:
- I don't think this is a regression.

[Notes]:
- This only happens when the pref extensions.fxmonitor.warnedHosts is populated. On a clean profile is not reproducing.

- Please look at the attached gif. 
![peek 2018-08-29 17-12](https://user-images.githubusercontent.com/42799381/44793349-b7234000-abae-11e8-95ef-ebbdedc4ee98.gif)

![peek 2018-08-29 17-02](https://user-images.githubusercontent.com/42799381/44792837-7676f700-abad-11e8-9ca6-3b80ccac5b76.gif)

**Comment by nhnt11** [comment]
Good catch, submitted PR #108

**Comment by obotisan** [comment]
@nhnt11  I've also noticed that the issue reproduces even when the add-on is removed from about:addons. You have to restart the browser in order for the doorhanger not to be displayed. 
Should we file a different bug for this issue or it's going to be fixed by this patch?

**Comment by nhnt11** [comment]
It will be fixed by this patch.

**Comment by obotisan** [comment]
We verify the fix using RC 62.0 -build 2 on Windows 10 x64, Ubuntu 16.04 x64 an Mac OS 10.11. The bug is not reproducing anymore.
