### ISSUE TITLE
The doorhanger's elements <number> and <year> are not bolded 

### ISSUE THREAD

**Issue by CiprianGeorgiu** [mozilla/blurts-addon#107]
[Affected versions]:
- latest Nightly 63.0a1
- DevEdition 63.0b1
- RC 62.0
- Firefox Monitor 2.1

[Affected platforms]:
- Windows 10 x64
- macOS 10.13
- Ubuntu 16.04 x64

[Prerequisites]:
Prefs you'll need to set in about:config:
- (boolean) extensions.fxmonitor.enabled - true
- (string) extensions.fxmonitor.breachListURL - https://haveibeenpwned.com/api/v2/breaches

[Steps to reproduce]:
- Launch Firefox.
- Navigate to a breached website: https://diet.com/
- Inspect the doorhanger's elements: "number" and "year".

[Expected result]:
- The doorhanger’s elements: number and "year" is displayed bolded.

[Actual result]:
- The doorhanger’s elements: "number" and "year" are not displayed bolded.

[Regression range]:
- Not a regression.

[Additional notes]:
- See the differences between UX spec and actual result:
![issue - bold number and year](https://user-images.githubusercontent.com/24842369/44793750-acb57600-abaf-11e8-8d52-43eea08e5479.png)

**Comment by nhnt11** [comment]
Ah, I spoke to UX about this and they agreed that bolding was not necessary (quite annoying to do this with formatted strings).

Closing.
