### ISSUE TITLE
URLEncode the query params in warnIfNeeded() method?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#12]
Specifically `doc.defaultView.openTrustedLinkIn("http://fx-breach-alerts.herokuapp.com/?breach=" + host, "tab"); `

Also, we should make sure that URL is HTTPS (once we change it to final URL &mdash; which I believe is issue #6)

https://github.com/mozilla/blurts-addon/blob/55cc9e26f603d20122b1a27dec693da776b39fd6/api/api.js#L88-L96

**Comment by nhnt11** [comment]
Fixed in #101
