### ISSUE TITLE
Set up localization in Pontoon

### ISSUE THREAD

**Issue by flodolo** [mozilla/blurts-addon#121]
From IRC discussion with @nhnt11, we want to use Pontoon to localize this add-on using a branch.

I'll need to know:
* Name of the branch
* Deadline
* Instructions on how to test the add-on, if possible

In order to allow write to the repository, [Pontoon's bot](https://github.com/mozilla-pontoon) will need to be added to the repository and have write access.

Also cc @mathjazz as an FYI, since he'll receive the notification for the bot.

**Comment by nhnt11** [comment]
I created an "l10n" branch and added the Pontoon bot to the repo with write access. Stay tuned for the deadline and a readme update.

**Comment by flodolo** [comment]
Note: this depends on #120

**Comment by flodolo** [comment]
[Push from stage worked](https://github.com/mozilla/blurts-addon/commit/1039e085be045f4b14e3ff49c762594177dd56e9), waiting for one more doubt before enabling prod.

I'll use [this list](https://github.com/mozilla/blurts-server/issues/524) for the initial list of languages, expect a lot of them to opt in.

**Comment by flodolo** [comment]
This is now done
https://pontoon.mozilla.org/projects/firefox-monitor-add-on/
