### ISSUE TITLE
"Firefox Monitor" add-on is not working after a browser restart

### ISSUE THREAD

**Issue by obotisan** [mozilla/blurts-addon#131]
[Affected versions]:
Firefox 63.0.1
Firefox 64.0b7
Firefox Monitor 2.5

[Affected Platforms]:
Windows 10 x64
Windows 7 x64
macOS 10.13
Ubuntu 18.04 x64

[Prerequisites]:
- Prefs you'll need to set in about:config:
(boolean) extensions.fxmonitor.enabled - true
(boolean) extensions.fxmonitor.debug - true
- Restart
- Install the add-on: https://drive.google.com/file/d/1P3STM5zoUstEGp1tPUhyBiCrhNb-C4ng/view?usp=sharing

[Steps to reproduce]:
1. Launch Firefox.
2. Navigate to the following breached website: https://www.linkedin.com/.
3. Restart Firefox (or close it and reopen it).
4. Go to any site that has breaches within 2 months (e.g. facepunch.com). 

[Expected result]:
- The doorhanger is triggered after the website is loaded.

[Actual result]:
- The doorhanger is not displayed after the website is loaded.

[Regression]:
- Not a regression.

[Notes]:
- If you check in about:config, the pref extensions.fxmonitor.warnedHosts contains only the sites that triggered the site before the restart.

**Comment by groovecoder** [comment]
FWIW I just did a spot-check of the 2.7 signed add-on attached at https://bugzilla.mozilla.org/show_bug.cgi?id=1486874#c46 and this seems to be fixed.

**Comment by GeorgiuCiprian** [comment]
We can also confirm that this issue is fixed on the 2.7 signed version of the add-on. Tested on 63.0.1 and 64.0b7 across platforms: Windows 10 x64, Windows 7 x86, macOS 10.13 and Ubuntu 18.04 x64.

**Comment by nhnt11** [comment]
Marked this as Verified Fixed based on https://github.com/mozilla/blurts-addon/issues/131#issuecomment-437006776
