### ISSUE TITLE
Remove website logos?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#15]
They seem to be inconsistently sized, and look _really_ bad in certain cases, such as:

![xboxscene](https://user-images.githubusercontent.com/557895/41631101-9db22c3e-73e7-11e8-80a8-8c7322649386.png)

Not sure if there is a good CSS way to scale the images to whatever size we have currently, but maintain aspect ratio. I'd rather the logo be scaled and illegible than stretched and illegible.

---

**UPDATE:** And here's what the breach currently looks like on https://blurts-server.stage.mozaws.net/?breach=Xbox-Scene

![firefox_monitor_xbox-scene](https://user-images.githubusercontent.com/557895/41633545-5556bb78-73f4-11e8-9fc9-db9ea5d83ba0.png)

**Comment by nhnt11** [comment]
Yeah, we can fix this, thanks for filing this.

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/blurts-server/issues/140

**Comment by pdehaan** [comment]
The add-on also has the same "transparent" white-on-white affect that the server has (ref https://github.com/mozilla/blurts-server/issues/208).

![telecom_regulatory_authority_of_india](https://user-images.githubusercontent.com/557895/41631064-68e1baba-73e7-11e8-83bf-9dbdadd9b84f.png)

**Comment by nhnt11** [comment]
We're not showing logos anymore.
