### ISSUE TITLE
Date formats are inconsistent between add-on and website

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#16]
| ADD-ON | SERVER |
|----|----|
| ![xboxscene](https://user-images.githubusercontent.com/557895/40928226-a9a950b2-67d5-11e8-8cc9-401e83b8b1ab.png) | ![firefox_monitor_-xbox-scene](https://user-images.githubusercontent.com/557895/40928296-cd890464-67d5-11e8-8905-bf425f01392e.png)
| **Figure 1:** "2015-02-01" | **Figure 2:** "February 1, 2015"

I believe the blurts-server date formatting code is here:
https://github.com/mozilla/blurts-server/blob/d963172fdc5fe3b5dc5d2a02977e5c109715d573/hbs-helpers.js#L6-L9

**Comment by pdehaan** [comment]
Actually, a few other minor nits after staring at the side-by-side screenshots:

- "Breach date" versus "Breach Date"
- "Compromised data" versus "Compromised Data"
- "Compromised accounts" versus "Compromised Accounts"
- The "Compromised data" and "Compromised accounts" sections are reversed.
- The titled are slightly different "Xbox-Scene" versus "Xbox-Scene Breach"

Let me know if you'd rather I file some of those against blurts-server instead. I'm not saying one is righter than the others, but we should be consistent as much as possible.

**Comment by lesleyjanenorton** [comment]
I think Title makes more sense and I'll change the other stuff too. Are we dropping the colons as well?

**Comment by pdehaan** [comment]
Don’t know about colons, maybe we need to ask a designer (or you can make the exec decision). As long as we’re consistent, I’m happy.

**Comment by nhnt11** [comment]
No longer relevant.
