### ISSUE TITLE
Confusing behavior when searching Firefox Monitor from add-on popup

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#17]
![xat-ffm](https://user-images.githubusercontent.com/557895/40929168-cd99cbac-67d8-11e8-86e9-d82adaae7364.png)

I clicked the big blue button without entering an email address, because I was expecting it to take me to more details (ie: https://fx-breach-alerts.herokuapp.com/?breach=xat)
But instead, the page lets me click the button, closes the door-hanger, and basically does nothing. So now when I refresh the page, it won't display the doorhanger again, so I have no link back to Firefox Monitor or no notifications that the site has been breached.

Not sure if we should consider any of the following:

1. Show the dialog on every page load until the user dismisses (although that seems aggressive).
1. Add a toolbar icon, that lights up when you're on a site with a known breach.

Here's what I see on subsequent page loads (note that it's missing that second little (i) icon):

![xat-refresh](https://user-images.githubusercontent.com/557895/40929425-80b20024-67d9-11e8-8711-e956c57ce2d0.png)

**Comment by nhnt11** [comment]
I don't think this is relevant anymore.
