### ISSUE TITLE
Clicking the down arrow in the dismiss split button causes the email address to be erased

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#18]
### Steps to reproduce:
1. Go to https://www.2fast4u.be/
1. Fill in an email address (but don't submit).
1. Click the "V" button in the "Dismiss" split button

### Actual results:
The email address is erased when you click the Dismiss button:

![2fast4u](https://user-images.githubusercontent.com/557895/40929804-b7ab6646-67da-11e8-8517-c64bb335cb39.gif)

**Comment by nhnt11** [comment]
No longer relevant :)
