### ISSUE TITLE
doc.defaultView.openTrustedLinkIn is not a function

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#19]
Still need to do some debugging on how/when this appeared in my log, but I was playing around w/ submitting my email address and clicking the blue button...

![ffmon](https://user-images.githubusercontent.com/557895/40929934-0f62201e-67db-11e8-9f11-6152446c1abd.png)

Link goes to view-source:moz-extension://59824a7a-6539-054a-941b-069b44f2dc0e/privileged/blurts/FirefoxMonitor.jsm

https://github.com/mozilla/blurts-addon/blob/c3d5bd3812e3fa108da64337e37c50b437208763/src/privileged/blurts/FirefoxMonitor.jsm#L390-L396

I'm also not clever enough to understand what `this._textbox.value` is, and if it needs to be URL-encoded since we're sending it along via a query string, or if it's already URL-safe.

**Comment by lesleyjanenorton** [comment]
I have been going through this for an hour. openUILinkIn works in stable, not in Nightly. openWebLinkIn works in Nightly, not in stable.

**Comment by lesleyjanenorton** [comment]
I am scared to even open Beta.

**Comment by nhnt11** [comment]
This works in 62, which is what we're targeting. I don't think we should support pre-62 releases.
