### ISSUE TITLE
Empty doorhanger when you switch tabs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#21]
### STR:
1. Go to https://bell.ca (but don't dismiss doorhanger)
1. Open a new tab, and go to http://r2games.com (but don't dismiss doorhanger)
1. Switch back to the Bell Canada tab.
1. Switch back to the R2 Games tab.

### Actual results:
The doorhanger is still open after switching tabs, but all the content is missing.

![r2-games-blank](https://user-images.githubusercontent.com/557895/41053136-9f8ce4f4-696f-11e8-831e-996a285e53f4.png)

I can't find any way of forcing a re-render on the Firefox Monitor doorhanger to get it to re-render contents after switching tabs.

**Comment by nhnt11** [comment]
This is fixed.
