### ISSUE TITLE
The "So far, so good" page is wrongly displayed if you click the "Search Firefox Monitor" button even if you entered a compromised email address or an invalid one

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/blurts-addon#25]
[Affected versions]:
- Firefox 60.0.2
- Firefox Monitor 0.01, Branch 2, Branch 3, Branch 5

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor [Branch 2] installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a breached website (eg: https://126.com).
3. Introduce a compromised (eg. test@example.com) email address.
4. Click the "Search Firefox Monitor" button and observe the behavior.

[Expected result]:
- The Firefox Monitor positive result page is opened in a new focused tab.

[Actual result]:
- The "So far, so good" negative result page is opened in a new focused tab. 

[Notes]:
- This issue is also reproducible if you insert an invalid email address (eg: example@test). A descriptive tooltip should be displayed, informing the user that he should enter a valid email address.
- This issue is also reproducible if you click the button without entering an email address. See also #17.
- This issue is not reproducible if you scan the compromised email address from the “https://fx-breach-alerts.herokuapp.com” page.
- Here is a screen recording with this issue:
![firefox monitor branches 2 3 5 - so far so good page](https://user-images.githubusercontent.com/31244235/41403756-56540438-6fce-11e8-95ac-5719e95381c6.gif)

**Comment by Softvision-CristinaBadescu** [comment]
This issue has been partially fixed: 
- if I perform a search with the invalid email address: eg. test@test, I'm redirected to the Firefox Monitor positive results page; for any other invalid email address (eg. hshsh@est), I am redirected to the negative result page;
- if I perform a search without entering any email, I'm redirected to the Firefox Monitor general landing page.

Tested using the latest version of the "Firefox Monitor" add-on (0.01 custom built on 27.06.2018), on Firefox Release 61.0 and Firefox Beta 62.0b3, on Windows 7 x64.

Considering this, I'm going to reopen the issue.
![breach alerts - issue 25 partially fixed](https://user-images.githubusercontent.com/31244235/41983143-e1d1f7a6-7a35-11e8-80e8-5dd234fbceb4.gif)

**Comment by nhnt11** [comment]
This issue is related to our website/deployment. This is not an issue with the addon. The issues with submitting a blank/invalid email have been fixed by f3d459d and 4434e55

**Comment by Softvision-CristinaBadescu** [comment]
This issue is no longer reproducible using the latest "Firefox Monitor" add-on (0.01 custom built on 28.06.2018), on Firefox Release 61.0 unbranded build. Verified on Windows 7 x64.
