### ISSUE TITLE
All checkboxs and email fields from doorhangers are wrongly deselected/cleared if you switch tabs

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/blurts-addon#26]
[Affected versions]:
- Firefox 60.0.2
- Firefox Monitor 0.01, All Branches

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor [Branch 4] installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a breached website (eg: https://126.com).
3. Type an email address and check the "Sign up for Firefox Monitor alerts" checkbox.
4. Open a new tab.
5. Switch back to the breached website tab and observe the Firefox Monitor doorhanger.

[Expected result]:
- The doorhanger contains the previously typed email address.
- The checkbox remains checked.

[Actual result]:
- The doorhanger no longer contains the previously typed email address.
- The checkbox is unchecked.

[Notes]:
- This issue is also reproducible for the "Feedback" doorhanger, if you check at least one answer.
- Here is a screen recording with this issue:
![email addres and checkbox unchecked - bug 3](https://user-images.githubusercontent.com/31244235/41404124-0eb510bc-6fcf-11e8-835b-1f2f6cadd3d1.gif)
![feedback form - deselect the selected options - bug 3](https://user-images.githubusercontent.com/31244235/41404133-129de87a-6fcf-11e8-8f2b-56d0c3d47b67.gif)

**Comment by nhnt11** [comment]
This is going to be quite complicated to fix, I'd rather not bother for the shield study.

**Comment by nhnt11** [comment]
No longer relevant.
