### ISSUE TITLE
No warning message is displayed if the feedback survey is submitted without checking any option

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#29]
**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 14.06.2018) installed.

**[Steps to reproduce]:**
1. Open a new private window and navigate to a breached website (eg. "https://www.avast.com").
2. Click the "Dismiss" button from the bottom right part of the doorhanger.
3. Click the "Submit" button and observe the behavior.

**[Expected result]:**
- A warning message is displayed.

**[Actual result]:**
- The doorhanger is dismissed.

**[Notes]:**
- Attached a screenshot of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41404445-e8f7deb2-6fcf-11e8-91a9-2b3d782f1848.gif)

**Comment by nhnt11** [comment]
No longer relevant.
