### ISSUE TITLE
The "x" button from doorhangers is not centered in the right corner

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/blurts-addon#32]
[Affected versions]:
- Firefox 60.0.2
- Firefox Monitor 0.01, All Branches

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a breached website (eg: https://126.com).
3. Observe the "x" button position from the doorhanger.

[Expected result]:
- The button is centered in the right corner.

[Actual result]:
- The button is slightly positioned further to the left part of the right corner.

[Notes]:
- Here is a screenshot with this issue:
![variation 1 - pop up](https://user-images.githubusercontent.com/31244235/41404940-2d342fa8-6fd1-11e8-83b3-fa4c320f9719.png)

**Comment by nhnt11** [comment]
Fixed in df54d256760b00afb40b4703f14bab5d5c2d6994 by simply hiding the x button.
