### ISSUE TITLE
The "Firefox Monitor" shield study wrongly works on the "Private Browsing" mode

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#33]
**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 14.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Open a new private window and navigate to a breached website (eg. "https://www.avast.com").
3. Observe the behavior.

**[Expected result]:**
- The doorhanger is not displayed.

**[Actual result]:**
- The doorhanger is displayed.

**[Additional Notes]:**
- The study's specific pings are also displayed in the "about:telemetry" page.
- This issue is reproducible on all the study's branches.
- Attached a screenshot of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41405200-d83ac36c-6fd1-11e8-9700-cf5573d1f2b7.gif)

**Comment by nhnt11** [comment]
I asked about this in #fx-team and #telemetry and was told that as long as we aren't tracking what site the user was on or whether or not they were in PBM, counting things is fine. So we can leave this as it is.
