### ISSUE TITLE
The "Firefox Monitor" doorhanger cannot be dismissed by pressing the "Esc" key, on websites that require "Adobe Flash"

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#36]
**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 15.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a breached website that requires flashplayer (eg. https://bitly.com/).
3. Press the "Esc" key and observe the doorhanger.

**[Expected result]:**
- The doorhanger is dismissed.

**[Actual result]:**
- The doorhanger is still displayed.

**[Additional Notes]:**
- The doorhanger can be dismissed if the tab is switched to another one and back.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41465688-d7b74e20-70a7-11e8-9626-b71b11f1b528.gif)

**Comment by nhnt11** [comment]
Hah, this is a bug in Firefox's PopupNotifications.jsm. I'm not sure there's an easy way around it. I don't think it belongs in this repository.
