### ISSUE TITLE
The typing area of the e-mail filed is limited to half its size, if the browser is resized when the doorhanger is open

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#38]
**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 15.06.2018) installed.
- Have the browser maximized.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a breached website (eg. https://bitly.com/).
3. Resize the browser and type a long string in the doorhanger's email field.
4. Observe the behavior.

**[Expected result]:**
- The string is correctly displayed in the email field.

**[Actual result]:**
- The string is displayed only until the middle of the field.

**[Additional Notes]:**
- The issue is still reproducible after the browser is maximized.
- This issue is reproducible on branches two, three and five.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41477844-3f48b30a-70ce-11e8-8837-d1dabbd6c846.gif)

**Comment by nhnt11** [comment]
This seems to be an extreme edge case. To encounter this issue, a user would have to:
- encounter the popup by navigating to a breached site
- get the urge to resize their browser, before finishing the interaction with the popup
- type in an email address that is longer than half the length of the textbox.

Based on this I don't consider this a major issue.

**Comment by nhnt11** [comment]
Actually, I don't think I'm going to end up fixing this in the add-on. It will probably be addressed if/when this variant is implemented into mozilla-central.
