### ISSUE TITLE
The "Firefox Monitor" hyperlink from the doorhanger doesn't redirect the user to the landing page with website details

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#44]
**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom build created on 18.06.2018) installed.
- You are enrolled on branch 2, 3 or 5.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a breached website (eg. https://www.adobe.com/#).
3. Click the "Firefox Monitor" hiperlink from the doorhanger's description.
4. Observe the behavior.

**[Expected result]:**
- You are redirected to the landing page with website details.

**[Actual result]:**
- You are redirected to the general landing page.

**[Additional Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41541912-424fe92e-731c-11e8-8e7a-c8271cfbd3b2.gif)

**Comment by pdolanjski** [comment]
I wouldn't block the study on this issue.  It's a minor problem.

**Comment by SoftVision-CarmenFat** [comment]
While we agree that this issue is not a blocker from the users point of view, we still consider it at least a major issue from the study's flow perspective, since there isn't any other way for users to access the landing page with website details.

**Comment by Softvision-MariusComan** [comment]
I am unable to verify this issue, because I'm blocked by the following one: #51 .
Considering this I am reopening this issue.

**Comment by Softvision-MariusComan** [comment]
I have retested this issue and it seems that it is partially fixed. You are still redirected on the general landing page from certain websites, such as: "https://8tracks.com/", "https://flvs.net/" and "http://www.underworldempireforums.com/".

**Comment by nhnt11** [comment]
Should be fixed now. We re-loaded the breach data on the server side.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Monitor" add-on (1.0 custom built on 29.06.2018) installed, on the latest Firefox release (61.0). Verified on Windows 10 x64.
