### ISSUE TITLE
The previously scanned email is not displayed anywhere in the text from the results page

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/blurts-addon#45]
[Affected versions]:
- Firefox 60.0.2
- Firefox Monitor 0.01, all Branches

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a breached website (eg. https://bitly.com/).
3. Type a valid email address in the doorhanger's email field.
4. Observe the scan results page.

[Expected result]:
- The scanned email is displayed at the beginning of the text, under the title.

[Actual result]:
- The scanned email is not displayed anywhere in the text.

[Additional notes]:
- Added a screen recording with the issue:

![email not shown](https://user-images.githubusercontent.com/26000308/41542887-97cdef8e-731e-11e8-87ee-6fc8ec5d50dc.gif)

**Comment by pdehaan** [comment]
I think this is by design. If I recall correctly, we only get a hash of the email and we don’t actually know /store the user’s email address.

**Comment by nhnt11** [comment]
Yup. Let's keep this issue open though, we can potentially solve this using local storage.

**Comment by nhnt11** [comment]
No longer relevant on this repo
