### ISSUE TITLE
A search can be wrongly performed, even if the email input field is empty

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#46]
**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom build created on 18.06.2018) installed.
- You are enrolled in branch 2, 3 or 5.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a breached website (eg. https://bitly.com/).
3. Click the "Search Firefox Monitor" button and observe the behavior.

**[Expected result]:**
- An error message that states the user to enter a valid email is displayed.

**[Actual result]:**
- The user is redirected to the "General" landing page.

**[Additional Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41544026-a8300e8c-7320-11e8-83b3-fb143e73a31d.gif)

**Comment by nhnt11** [comment]
Fixed by 4434e55

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Monitor" add-on (1.0 custom built on 28.06.2018) installed, on the latest Firefox release (61.0). Verified on Windows 10 x64.
