### ISSUE TITLE
Required argument triggeringPrincipal missing within openUILinkIn

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#47]
### Steps to reproduce:
1. Install breach alerts add-on.
1. Go to http://www.126.com
1. Click the "Go to Firefox Monitor" button.
1. Open Browser console.

### Actual results:
Nothing happens. I'm not redirected to Firefox Monitor site.
Following error appears in the browser console:

> Required argument triggeringPrincipal missing within openUILinkIn (chrome://browser/content/utilityOverlay.js)
> &nbsp;&nbsp; openUILinkIn
> &nbsp;&nbsp; chrome://browser/content/utilityOverlay.js:264:11
> &nbsp;&nbsp; UIFactory</retval.primaryAction.callback<
> &nbsp;&nbsp; moz-extension://91ad29e2-59ff-ac4a-9892-8152fc6bb857/privileged/blurts/FirefoxMonitor.jsm:479:9
> &nbsp;&nbsp; &lt;anonymous&gt; self-hosted:986:17 _onButtonEvent
> &nbsp;&nbsp; resource://gre/modules/PopupNotifications.jsm:1543:9
> &nbsp;&nbsp; oncommand    chrome://browser/content/browser.xul:1:1

```js
function openUILinkIn(url, where, aAllowThirdPartyFixup, aPostData, aReferrerURI) {
  var params;

  if (arguments.length == 3 && typeof arguments[2] == "object") {
    params = aAllowThirdPartyFixup;
  } else {
    throw new Error("Required argument triggeringPrincipal missing within openUILinkIn");
  }

  params.fromChrome = true;

  openLinkIn(url, where, params);
}
```

**Comment by pdehaan** [comment]
I'm seeing the same issue w/ the "Firefox Monitor" and "Privacy Policy" links in the doorhanger:

![openuilinkin](https://user-images.githubusercontent.com/557895/41630281-0dfcf794-73e3-11e8-8ebc-fbeb5aab1558.png)

**Comment by lesleyjanenorton** [comment]
this is working for me in stable and nightly.
`doc.defaultView.openUILinkIn("http://localhost:6060/?breach="+ host, "tab");`

 will push as soon as I get the tabbing issue resolved!

**Comment by lesleyjanenorton** [comment]
Fixed! I haven't checked it Beta yet but I have it working in Stable and Nightly
