### ISSUE TITLE
[Branch 4] "Go to Firefox Monitor" button from the doorhanger wrongly redirect the user to landing page with website details

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#49]
**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 19.06.2018) installed.
- You are enrolled in branch 4.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to a breached website (eg. https://bitly.com/).
3. Click the "Go to Firefox Monitor" doorhanger's button.
4. Observe the behavior.

**[Expected result]:**
- The general landing page is opened.

**[Actual result]:**
- The landing page with website details is opened.

**[Additional Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41597623-a5af05a8-73d6-11e8-9f1f-adc494660c8e.gif)

**Comment by lesleyjanenorton** [comment]
Hi Marius, this is actually the desired behavior when the 'Go to Firefox Monitor' button is clicked from a site with breaches. In watching your screen cast though, I can see why this might be confusing as because the verbiage 'Go to Firefox Monitor' doesn't specifically indicate that the user will be taken to view more details about a specific breach.

**Comment by Softvision-MariusComan** [comment]
Hi Lesley, the "[Firefox Monitor User flow](https://docs.google.com/presentation/d/1udCP6jp1RUAxCpverqU4N6TFdVJi50e_MaIkJSXIuaE/edit#slide=id.g3ad463f40b_0_202)" document specifies that clicking the "Go to Firefox Monitor" button (Branch 4) should redirect the user to the General landing page.

**Comment by Softvision-MariusComan** [comment]
I am unable to verify this issue, because I'm blocked by the following one: #52 .
Considering this I am reopening this issue

**Comment by nhnt11** [comment]
This has been fixed.

**Comment by nhnt11** [comment]
branch 4 is now shown only on the newtab page and links to the general landing page.

**Comment by Softvision-MariusComan** [comment]
This issue is no longer reproducible with the latest version of the "Firefox Monitor" add-on (1.0 custom built on 28.06.2018) installed, on the latest Firefox release (61.0). Verified on Windows 10 x64.
