### ISSUE TITLE
[Beta 61] "Go to Firefox Monitor" button from Branches 1 and 4 doesn't open the landing page with website's details about the breach

### ISSUE THREAD

**Issue by SoftVision-CarmenFat** [mozilla/blurts-addon#52]
[Affected versions]:
- Firefox Beta 61.0b14
- Firefox Monitor 0.01, Branches 1 and 4

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a clean Firefox profile with the latest Firefox Monitor v0.01 (custom built on 2018-06-20) installed.

[Steps to reproduce]:
1. Open the Firefox browser with the profile from prerequisites.
2. Navigate to a breached website (eg. https://bitly.com/).
3. Click the "Go to Firefox Monitor" button from the doorhanger.
4. Observe what happens next.

[Expected result]:
- The user is redirected to the Firefox Monitor Landing Page with website's details about the breach.

[Actual result]:
- Nothing happens, the Landing Page with details about the breach is not opened.

[Additional notes]:
- This issue is not reproducible on Firefox Release 60.0.2.
- Added a screen recording with the issue:

![button doesn t open page](https://user-images.githubusercontent.com/26000308/41649636-b3a2a544-7484-11e8-93fd-cbd14ee6a7a2.gif)

**Comment by SoftVision-CarmenFat** [comment]
Tested this with the latest Breach Alerts add-on (custom build on 06/27/2018) and the issue is still reproducible. Considering this, I'm going to reopen the issue.

**Comment by SoftVision-CarmenFat** [comment]
Tested this with the latest Breach Alerts add-on (custom build on 06/27/2018) and the issue is still partially reproducible. After clicking the "Go to Firefox Monitor" button, a new tab is opened but it's blank.
Considering this, I'm going to reopen the issue.

![branches 1 and 4](https://user-images.githubusercontent.com/26000308/41985637-8f4f2556-7a3c-11e8-83b1-d09482ec8be6.gif)

**Comment by nhnt11** [comment]
Fixed by f7ce8f8 and 33ac7dd

**Comment by SoftVision-CarmenFat** [comment]
Tested this with the latest Breach Alerts add-on (custom build on 06/28/2018) and the issue is no longer reproducible. Clicking the "Go to Firefox Monitor" button redirects the user to the Landing Page with websites results, as expected.
