### ISSUE TITLE
The "Sign up for alerts" pop-up from the "Firefox Monitor" website cannot be dismissed by any other methods except the "Close" button

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#53]
**[Affected versions]:**
- Firefox 60.0.2

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 20.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to the "https://fx-breach-alerts.herokuapp.com/" page.
3. Click the "Sign up for alerts" button.
4. Press the "Esc/Enter" key or click outside the pop-up area.
5. Observe the behavior.

**[Expected result]:**
- The pop-up is dismissed.

**[Actual result]:**
- Nothing happens.

**[Notes]:**
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41655176-afa1ca64-7494-11e8-9a86-0d16069ea7dd.gif)

**Comment by e-pang** [comment]
@Softvision-MariusComan thanks for flagging this bug!

@lesleyjanenorton Would be great to have all three of these interactions if possible to dismiss the pop up. But if too much work not crucial to the shield study. 

1. Press the Esc Key
2. Oress Enter Key
3. Click outside the pop-up area.

**Comment by nhnt11** [comment]
This is not related to the add-on, could you please file this in https://github.com/mozilla/blurts-server/issues

**Comment by lesleyjanenorton** [comment]
hey @e-pang, @Softvision-MariusComan  hey guys! I have made these changes in blurts-server and as soon as PR #209 we should be able to see them. Thanks!

**Comment by pdehaan** [comment]
Moved to https://github.com/mozilla/blurts-server/issues/215
