### ISSUE TITLE
Easier way to allow QA to opt in to a specific variant

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#56]
Currently it seems like we either have to relaunch and reinstall the add-on in hopes we get put into the variant we want to test, or else comment out the variants we _don't_ want so only one variant remains.

Not sure if there is an easier/better way of setting the variant in **about:config** and having the add-on check for an assigned variant before choosing one randomly.

Or maybe this won't be an issue after shield launch since we may only have one variant remaining at that point.

**Comment by nhnt11** [comment]
No longer relevant.
