### ISSUE TITLE
Change links to server to monitor.firefox.com

### ISSUE THREAD

**Issue by groovecoder** [mozilla/blurts-addon#6]

**Comment by pdehaan** [comment]
@Micheletto Just confirming, but is the final production name for the blurts-server going to be "monitor.firefox.com"?

**Comment by Micheletto** [comment]
Yes.

**Comment by Micheletto** [comment]
> Looks like prod server is live! https://monitor.firefox.com/__version__

This version, however, is using the same configuration settings as stage.  I need the production values to plug in for the following settings:

-    COOKIE_SECRET
-    DEBUG_DUMMY_SMTP
-    HIBP_API_ROOT
-    HIBP_API_TOKEN
-    HIBP_STAGE_API_ROOT
-    HIBP_STAGE_API_TOKEN
-    HIBP_STUB_API_ROOT

**Comment by Micheletto** [comment]
> DEBUG_DUMMY_SMTP

Actually, I think we just don't set this one in production.
