### ISSUE TITLE
Shield bits

### ISSUE THREAD

**Issue by gregglind** [mozilla/blurts-addon#61]
(Shield engineering review, based on `qa-fixes` branch)

See:  https://github.com/mozilla/shield-studies-addon-template/  for some of these

As a SHIELD deployer, I want to know
- [x] What Telemetry (if any) is being sent and when.  This is normally in `docs/TELEMTRY.md`.
- [x] Surveys, if any?  Are they all 'endpoint' surveys, or are their midpoint ones?
- [x] Confirm that the current / live version of mozilla/shield-study-addon-utils is there.  The current usual pattern is a `package.json`.

**Comment by gregglind** [comment]
About Surveys:

- urls to open, such as Surveys, come along *with appended query args* as part the `endStudy` signal.  The Appended query args conform to how Mozilla generally does surveys.

See example: https://github.com/mozilla/shield-cloudstorage/blob/master/webextension/background.js#L115-L125
And in the code:  https://github.com/mozilla/shield-cloudstorage/blob/master/webextension/background.js#L115-L125

**Comment by nhnt11** [comment]
I've refactored the repo, and updated the telemetry doc. The shield-study-addon-utils stuff is done via the package.json mechanism so it'll always be the latest code. Will look into the survey stuff.

**Comment by nhnt11** [comment]
all of Gregg's concerns have been addressed and study endings have been implemented.
