### ISSUE TITLE
Add final survey ending URLs

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#62]
Per https://github.com/mozilla/blurts-addon/pull/57#discussion_r198229280 conversation, these aren't the final qsurvey URLs, and we should probably update them before the shield release:

https://github.com/mozilla/blurts-addon/blob/96d1b3039f490c0293a735c2cd296d5406f3f73a/src/background.js#L70-L86

**Comment by nhnt11** [comment]
fixed by d9bd854 and others
