### ISSUE TITLE
[Branch 3] The "Thank you" pop up appears on the Firefox Monitor results page after performing a search, when the "Sign up" checkbox was not previously selected

### ISSUE THREAD

**Issue by Softvision-CristinaBadescu** [mozilla/blurts-addon#67]
[Affected versions]:
- Firefox 61.0
- Firefox Monitor 0.01, Branch 3

[Affected Platforms]:
- All Windows

[Prerequisites]:
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 27.06.2018) installed.
- Be enrolled in Branch 3.

[Steps to reproduce]:
1. Open the browser and navigate to the "https://www.adobe.com/" page.
2. Type a valid email address in the Firefox Monitor doorhanger.
3. Click the "Search for Firefox Monitor" button and observe the behavior.

[Expected result]:
- Firefox Monitor result page is opened in a new focused tab.

[Actual result]:
- Firefox Monitor result page is opened in a new focused tab and the "Thank you" pop up is displayed.

[Notes]:
- According to the [User Flow documentation](https://docs.google.com/presentation/d/1udCP6jp1RUAxCpverqU4N6TFdVJi50e_MaIkJSXIuaE/edit#slide=id.g3ad463f40b_0_156), if the "Sign up" checkbox is not selected, the "Thank you" pop up should not be displayed on the Firefox Monitor result page.
- Here is a screen recording with this issue:
![breach alerts - thank you pop up](https://user-images.githubusercontent.com/31244235/41981075-c0d309aa-7a30-11e8-8037-1a774c09a24d.gif)

**Comment by lesleyjanenorton** [comment]
Hi Cristina, this is potentially an issue for blurts-server. I am taking a look at it right now and will open the issue in the blurts-server repo if so. Thanks for the catch!

**Comment by Softvision-CristinaBadescu** [comment]
Hey Lesley, as mentioned in the email sent by Carmen minutes earlier, I've encountered the issue using the Firefox Monitor custom build cloned from the wrong branch ("popup_variants"). The behavior is different using the custom build cloned from the "master" branch: when I  perform a search, I'm redirected to a blank page. It seems that this is the behavior on all branches.
![branch 3 - blank page](https://user-images.githubusercontent.com/31244235/41988420-baf1b324-7a44-11e8-9c44-0411ac716b04.gif)

**Comment by nhnt11** [comment]
Fixed by f7cadaa
