### ISSUE TITLE
The "Firefox Monitor" doorhangers are wrongly redisplayed on visited website after a browser restart

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/blurts-addon#68]
**[Affected versions]:**
- Firefox 61.0

**[Affected Platforms]:**
- All Windows

**[Prerequisites]:**
- Have a new Firefox profile with the latest version of the "Firefox Monitor" add-on (0.01 custom built on 27.06.2018) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites and navigate to the "https://www.avast.com" website.
2. Dismiss the study's doorhanger and the survey one.
3. Close and reopen the browser.
4. Navigate to the "https://www.avast.com" website again and observe the behavior.

**[Expected result]:**
- The "Firefox Monitor" doorhanger is no longer displayed.

**[Actual result]:**
- The "Firefox Monitor" doorhanger is displayed again.

**[Additional Notes]:**
- This issue is reproducible on all the study's branches.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/41985406-e1784700-7a3b-11e8-8a34-c1f6067a4970.gif)

**Comment by nhnt11** [comment]
Fixed by e6ed377
