### ISSUE TITLE
Optimize PwnedLogo PNGs?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#76]
Looks like we're doing some svgo magic in the **setup-breaches** npm script, but not sure if we want a similar PNG optimizer to make sure that the PNGs are as lean as possible.

https://github.com/mozilla/blurts-addon/blob/2e5c3d14ffad997e672159b80545cd438c323138/package.json#L49

```sh
$ ls -lash src/PwnedLogos/*.png | wc -l # 162
$ ls -lash src/PwnedLogos/*.svg | wc -l # 125
```

```js
    "optimize-assets": "npm-run-all -p optimize-assets:*",
    "optimize-assets:png": "imagemin src/PwnedLogos/*.png --out-dir=src/PwnedLogos",
    "optimize-assets:svg": "svgo src/PwnedLogos/*.svg -q",
```

**Comment by nhnt11** [comment]
Thanks for filing this. I attempted to do this with pngo/pngcrush but couldn't get past a complaint about the pngs not being valid pngs. If imagemin works, that's great, let's do it
