### ISSUE TITLE
Rethink how often we scrape breach data/logos from HIBP

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#77]
It looks like whenever you run <kbd>$ npm run build</kbd> to build your add-on, you're [possibly unknowingly] downloading the latest breach data (260 KB; src/breaches.json) and all the associated logos (3.7 MB; src/PwnedLogos/*.{png,svg}) and then minimizing the SVGs.  

Here's the general flow for `npm run build` (with the relevant "pre" hooks and related scripts):

```js
  "scripts": {
    [0] "prebuild": "npm run bundle-utils && npm run setup-breaches",
    [1] "bundle-utils": "copyStudyUtils src/privileged",
    [2] "setup-breaches": "node scripts/setup-breaches.js && node_modules/svgo/bin/svgo -q src/PwnedLogos/*.svg",
    [3] "build": "web-ext build",
  }
```

Not sure if there is a better hook we can use, or maybe a script that just specifically downloads and optimizes assets when you invoke it, instead of on every `npm run build` call, which may cause some unnecessary traffic to the HIBP server.

**Comment by nhnt11** [comment]
Hey, re "maybe a script that just specifically downloads and optimizes assets when you invoke it" that already exists: it's setup-breaches. I just added it to prebuild without thinking too much, I don't mind taking that out and making $npm run setup-breaches part of the repo setup instructions. Want to make a PR for this?
