### ISSUE TITLE
Variant 5 doorhanger text is duplicated in dropdown

### ISSUE THREAD

**Issue by pdehaan** [mozilla/blurts-addon#92]
(Via **fdjabri** in Slack)

FYI - the doorhanger for variant 5 in the user tests seems to be repeating info. I’m not sure if this is still an issue or if it needs to be fixed. FWIW, it doesn’t really seem to effect the user tests.

![adobe__creative__marketing_and_document_management_solutions](https://user-images.githubusercontent.com/557895/42606500-d94e65bc-8532-11e8-84c4-039be46173f0.png)

**Comment by nhnt11** [comment]
No longer relevant.
