### ISSUE TITLE
Data Review request

### ISSUE THREAD

**Issue by nhnt11** [mozilla/blurts-addon#95]
Please see docs/data-review.md for the data-review request document.

**Comment by nhnt11** [comment]
@chutten I believe you are the right person for this since you are the data-steward for Firefox telemetry. https://wiki.mozilla.org/Firefox/Data_Collection.

Please let me know if this request is incomplete and/or what other information I can provide! Thanks.

**Comment by nhnt11** [comment]
Data review doc: https://github.com/mozilla/blurts-addon/blob/master/docs/data-review.md
Telemetry doc: https://github.com/mozilla/blurts-addon/blob/master/docs/TELEMETRY.md

**Comment by chutten** [comment]
In actuality I'm a Data Steward and the team I'm on is called "Firefox Telemetry"... maybe I'd get fewer data review requests if I made that a little more clear on the wiki... :S

**Comment by nhnt11** [comment]
This was completed in https://bugzilla.mozilla.org/show_bug.cgi?id=1485650#c1
